image: Visual Studio 2017
before_build:
  nuget restore
configuration: Release
platform: Any CPU
nuget:
  project_feed: true
  disable_publish_on_pr: true
build:
  publish_nuget: true
  verbosity: minimal
after_build:
  dotnet pack NginxRTMP
artifacts:
  path: **\*.nupkg
